version: "3.7"
services:
    gateway:
        image: docker.pkg.github.com/yoki-labs/guilded_interaction/gateway
        container_name: GUILDED_INTERACTION_GATEWAY
        restart: unless-stopped
        env_file:
            - ./.env
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
