version: "3.7"
services:
    db:
        image: postgres
        restart: unless-stopped
        container_name: GUILDED_INTERACTION_DB
        environment:
            POSTGRES_DB: guilded_interaction
            POSTGRES_USER: guilded_interaction_user
            POSTGRES_PASSWORD: guilded_interaction_pass
        networks:
            - db-network
        volumes:
            - ginteractions-postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    gateway:
        build:
            context: .
            dockerfile: ./services/gateway/Dockerfile
        command: "yarn run dev"
        depends_on:
            - db
        volumes:
            - "./services/gateway/src:/usr/app/src"
        restart: "no"
        environment:
            DATABASE_URL: "postgresql://guilded_interaction_user:guilded_interaction_pass@db:5432/guilded_interaction?schema=public"
            SERVER_PORT: 3335
            TOKEN_SECRET: "super-secret-token"
        ports:
            - 3335:3335
        networks:
            - db-network
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    ginteractions-postgres-data:


networks:
    db-network:
        driver: bridge
    
